---
- hosts: web
  become: yes
  tasks:
    - name: install apache httpd 
      ansible.builtin.apt:
        name: apache2
        state: present 
        update_cache: yes
    - name: copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html # from the same directory as this playbook
        dest: /var/www/html
        owner: root
        group: root
        mode: 0644 
