---
- name: enforce s3 bucket versioning
  hosts: localhost
  gather_facts: false 

  tasks:
  - name: list all s3 buckets
    amazon.aws.s3_bucket_info:
    register: list_of_buckets

  - debug: 
      var: list_of_buckets

  - name: enable versioning on s3 buckets
    amazon.aws.s3_bucket:
      name: "{{ item.name }}"
      versioning: true
    loop: "{{ list_of_buckets.buckets }}"
